IncompleteVector = AbstractVector{<:Union{<:Real,Missing}}

# Suffix for internal type names generated by @generate_strategy / @generate_derivative,
# letting the public name be rebound to a fresh type on each macro call instead of
# redefining a struct in place (which Julia does not support for differing fields).
_unique_type_suffix() = string(rand(UInt32); base=16)

"""
    gbm_step(x::Real, mu::Real, sigma::Real; rng::AbstractRNG=Random.default_rng())

Next Geometric Brownian Motion price given current price `x`, drift `mu`, and volatility
`sigma` (both per-step). Strictly positive for `x > 0`.

```jldoctest
Random.seed!(1);
gbm_step(100.0, 0.0, 0.02)
# output

99.83896352519557
```
"""
function gbm_step(x::Real, mu::Real, sigma::Real; rng::AbstractRNG=Random.default_rng())
  return x * exp((mu - 0.5 * sigma^2) + sigma * randn(rng))
end

"""
    gbm_path(x0::Real, mu::Real, sigma::Real, n::Int; rng::AbstractRNG=Random.default_rng())

Length-`n` GBM path starting at `x0` (`path[1] == x0`, each subsequent value via `gbm_step`).

```jldoctest
Random.seed!(1);
gbm_path(100.0, 0.0, 0.02, 5)
# output

5-element Vector{Float64}:
 100.0
  99.83896352519557
 100.8856864256948
  99.25090240467883
 104.22904553825927
```
"""
function gbm_path(
  x0::Real, mu::Real, sigma::Real, n::Int; rng::AbstractRNG=Random.default_rng()
)
  path = Vector{Float64}(undef, n)
  path[1] = x0
  for i in 2:n
    path[i] = gbm_step(path[i - 1], mu, sigma; rng=rng)
  end
  return path
end

# Shared correlated-step math given an already-factored lower Cholesky `L`. `gbm_step`
# (multivariate) and `gbm_path` (multivariate) both call this; only `gbm_path` amortizes the
# factorization across an entire path.
function _gbm_step(x::AbstractVector{<:Real}, mu::AbstractVector{<:Real},
  sigma::AbstractVector{<:Real}, L::AbstractMatrix{<:Real}; rng::AbstractRNG)
  z = L * randn(rng, length(x))
  return x .* exp.((mu .- 0.5 .* sigma .^ 2) .+ sigma .* z)
end

"""
    gbm_step(x::AbstractVector{<:Real}, mu::AbstractVector{<:Real}, sigma::AbstractVector{<:Real}, rho::AbstractMatrix{<:Real}; rng::AbstractRNG=Random.default_rng())

Next correlated GBM prices for a vector of assets: drift `mu`, volatility `sigma`, and
correlation matrix `rho` (all per-step). Use `gbm_path` for a loop over multiple steps.

```jldoctest
Random.seed!(1);
gbm_step([100.0,50.0], [0.0,0.0], [0.02,0.03], [1.0 0.5; 0.5 1.0])
# output

2-element Vector{Float64}:
 99.83896352519557
 50.61876864985363
```
"""
function gbm_step(x::AbstractVector{<:Real}, mu::AbstractVector{<:Real},
  sigma::AbstractVector{<:Real}, rho::AbstractMatrix{<:Real};
  rng::AbstractRNG=Random.default_rng())
  L = cholesky(Symmetric(rho)).L
  return _gbm_step(x, mu, sigma, L; rng=rng)
end

"""
    gbm_path(x0::AbstractVector{<:Real}, mu::AbstractVector{<:Real}, sigma::AbstractVector{<:Real}, rho::AbstractMatrix{<:Real}, n::Int; rng::AbstractRNG=Random.default_rng())

Correlated GBM paths for `length(x0)` assets over `n` bars (`[n_assets × n_bars]`).

```jldoctest
Random.seed!(1);
gbm_path([100.0,50.0], [0.0,0.0], [0.02,0.03], [1.0 0.5; 0.5 1.0], 3)
# output

2×3 Matrix{Float64}:
 100.0  99.839   98.2211
  50.0  50.6188  53.2823
```
"""
function gbm_path(x0::AbstractVector{<:Real}, mu::AbstractVector{<:Real},
  sigma::AbstractVector{<:Real}, rho::AbstractMatrix{<:Real}, n::Int;
  rng::AbstractRNG=Random.default_rng())
  L = cholesky(Symmetric(rho)).L
  path = Matrix{Float64}(undef, length(x0), n)
  path[:, 1] = x0
  for i in 2:n
    path[:, i] = _gbm_step(path[:, i - 1], mu, sigma, L; rng=rng)
  end
  return path
end

"""
    gbm_path_segments(x0::Real, segments; rng::AbstractRNG=Random.default_rng())

Chain `gbm_path` across a list of regimes into one continuous series. Each element of
`segments` is a `(mu, sigma, n)` NamedTuple; each regime continues from the previous regime's
last price.

```jldoctest
Random.seed!(1);
gbm_path_segments(100.0, [(mu=0.0,sigma=0.02,n=3),(mu=0.1,sigma=0.3,n=2)])
# output

4-element Vector{Float64}:
 100.0
  99.83896352519557
 100.8856864256948
  83.67434009011494
```
"""
function gbm_path_segments(x0::Real, segments; rng::AbstractRNG=Random.default_rng())
  path = Float64[x0]
  x = x0
  for seg in segments
    seg_path = gbm_path(x, seg.mu, seg.sigma, seg.n; rng=rng)
    append!(path, @view seg_path[2:end])
    x = seg_path[end]
  end
  return path
end

"""
    gbm_path_segments(x0::AbstractVector{<:Real}, segments; rng::AbstractRNG=Random.default_rng())

Multivariate counterpart of `gbm_path_segments`. Each element of `segments` is a
`(mu, sigma, rho, n)` NamedTuple — `rho` may change between segments.

```jldoctest
Random.seed!(1);
gbm_path_segments([100.0,50.0], [(mu=[0.0,0.0],sigma=[0.02,0.03],rho=[1.0 0.5; 0.5 1.0],n=3)])
# output

2×3 Matrix{Float64}:
 100.0  99.839   98.2211
  50.0  50.6188  53.2823
```
"""
function gbm_path_segments(
  x0::AbstractVector{<:Real}, segments; rng::AbstractRNG=Random.default_rng()
)
  path = reshape(collect(Float64, x0), :, 1)
  x = x0
  for seg in segments
    seg_path = gbm_path(x, seg.mu, seg.sigma, seg.rho, seg.n; rng=rng)
    path = hcat(path, @view seg_path[:, 2:end])
    x = seg_path[:, end]
  end
  return path
end

# NaN is the sentinel for missing/gap data. All price/indicator arrays are
# plain Float64 — no boxing, SIMD-friendly, compatible with isnan() guards.
"""
    DataPoint

A single bar's worth of row values, one per dataset (`Vector{Float64}`).

```jldoctest
DataPoint([1.0,2.0])
# output

2-element Vector{Float64}:
 1.0
 2.0
```
"""
DataPoint = Vector{Float64}

"""
    DataSeries

A row × bar price/indicator matrix (`Matrix{Float64}`).

```jldoctest
DataSeries(undef,1,1) isa DataSeries
# output

true
```
"""
DataSeries = Matrix{Float64}

"""
    data_series(x::Vector{DataPoint})

Stack ragged data points into a `DataSeries`, right-padding shorter rows with NaN.

```jldoctest
data_series([[1.0,2.0],[1.0,2.0,3.0]])
# output

2×3 Matrix{Float64}:
 1.0  2.0  NaN
 1.0  2.0    3.0
```
"""
function data_series(x::Vector{DataPoint})
  isempty(x) && return DataSeries(undef, 0, 0)
  hght = length(x)
  lgth = maximum(length.(x))
  arr = fill(NaN, hght, lgth)
  for i in eachindex(x)
    n = length(x[i])
    for j in 1:n
      arr[i, j] = x[i][j]
    end
  end
  return arr
end

data_point(x::Vector{<:Real}) = DataPoint(x)
data_point(n::Int) = fill(NaN, n)

function add!(x::DataSeries, y::DataPoint; start=1)
  n = size(x, 2)
  new_n = max(n, length(y) + start - 1)
  new_x = fill(NaN, size(x, 1), new_n)
  new_x[:, 1:n] .= x
  for j in eachindex(y)
    new_x[end, start + j - 1] = y[j]
  end
  return new_x
end
